export const DEFAULT_SEND_AND_WAIT_TIMEOUT_SECONDS = 50;
export const MAX_SEND_AND_WAIT_TIMEOUT_SECONDS =
  DEFAULT_SEND_AND_WAIT_TIMEOUT_SECONDS;
export const DEFAULT_SEND_AND_WAIT_TIMEOUT_MS =
  DEFAULT_SEND_AND_WAIT_TIMEOUT_SECONDS * 1_000;
export const DEFAULT_SESSION_HELPER_COUNTDOWN_MS = 10 * 60 * 1_000;

export function clampSendAndWaitTimeoutSeconds(
  timeoutSeconds = DEFAULT_SEND_AND_WAIT_TIMEOUT_SECONDS,
): number {
  return Math.min(
    Math.max(timeoutSeconds, 0),
    MAX_SEND_AND_WAIT_TIMEOUT_SECONDS,
  );
}
